name: 🚀 Deploy to Cafe24 (Stable)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🚀 FTP Upload
        uses: burnett01/rsync-deployments@v7.0.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /www/
          remote_host: ${{ secrets.FTP_SERVER }}
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_key: ${{ secrets.FTP_PASSWORD }}